### ISSUE TITLE
Does mciro-http support Uri query part?

### ISSUE THREAD

**Issue by changweige** [firecracker-microvm/micro-http#10]
For example,
```
abc://username:password@example.com:123/path/data?key=value&key2=value2#fragid1
                                                  |-------------------|
                                                            |
                                                          query
```
I tried to fill URI with query part, but it responded with 404.

**Comment by andreeaflorescu** [comment]
Queries are not supported in micro-http. This crate is used by VMMs such as Firecracker and Cloud Hypervisor to provide a way for configuring virtual machines. Up till now, for the use cases that we know of, queries have not been required.

Do you plan to use micro-http?

**Comment by changweige** [comment]
> Queries are not supported in micro-http. This crate is used by VMMs such as Firecracker and Cloud Hypervisor to provide a way for configuring virtual machines. Up till now, for the use cases that we know of, queries have not been required.

I suppose I have a workaround now. I can directly use crate http to split the uri into parts(path query). 


> Do you plan to use micro-http?

Yes. we plan to integrate it into our project to fetch internal running state/metrics together with some tiny configuration stuff.
