### ISSUE TITLE
Receive ancillary data

### ISSUE THREAD

**Issue by sboeuf** [firecracker-microvm/micro-http#20]
At the moment, there's no support for any out-of-band mechanism in order to send ancillary data along with an HTTP request. The need for this feature is to be able to send file descriptors over the socket to the VMM process, allowing these file descriptors to be associated with a particular request.

In the Cloud Hypervisor context, we want to let the user provide a list of TAP file descriptors, which could be sent along with the HTTP request `add-net`, while the VMM might already be running.

The proper way to achieve this would be to rely on the ancillary data mechanism once it is accepted in Rust `stable`, and leverage it directly from the `UnixStream` object. This is still a `nightly` [feature](https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html#method.recv_vectored_with_ancillary), but I wanted to touch base on this topic to anticipate the discussion.

If we can agree it would be nice to have the `micro_http` support ancillary data, that means that any request could now contains a list of file descriptors associated with it. Do you think this is acceptable for the crate?

**Comment by acatangiu** [comment]
> If we can agree it would be nice to have the micro_http support ancillary data, that means that any request could now contains a list of file descriptors associated with it. Do you think this is acceptable for the crate?

Sounds good to me. Adding support for ancillary data when UDS is used as backend seems natural (right now `micro-http` supports _only_ UDS) and definitely useful.

**Comment by sboeuf** [comment]
> Sounds good to me. Adding support for ancillary data when UDS is used as backend seems natural (right now micro-http supports only UDS) and definitely useful.

Cool! Let's hope this feature does not take too long to land in Rust `stable` :)

**Comment by georgepisaltu** [comment]
@sboeuf can you ping us on this issue when the feature becomes stable?

**Comment by sboeuf** [comment]
Sure, I'll track this down.

**Comment by sboeuf** [comment]
@acatangiu @georgepisaltu 
One alternative to implement this feature without having to wait for Rust to provide the support for ancillary data would be to use `vmm-sys-util` crate which provides an equivalent implementation here: https://github.com/rust-vmm/vmm-sys-util/blob/master/src/linux/sock_ctrl_msg.rs
Instead of having the `stream` in `HttpConnection` implementing `Read` + `Write`, it could implement `ScmSocket` as well, meaning we could use `recv_with_fds()` instead of `read()`.
Because `UnixStream` already implements `ScmSocket`, this should be fairly straightforward.

WDYT of this approach in order to speed things up?

**Comment by acatangiu** [comment]
@sboeuf looks good to me

**Comment by sboeuf** [comment]
Ok cool, I'll give this a try when I get a chance :)

**Comment by sboeuf** [comment]
@acatangiu I submitted a PR to handle this issue, please let me know what you think about it!

**Comment by acatangiu** [comment]
This was fully implemented in https://github.com/firecracker-microvm/micro-http/pull/23
