### ISSUE TITLE
HTTP Pipelining

### ISSUE THREAD

**Issue by ibraheemdev** [firecracker-microvm/micro-http#21]
Does `micro-http` handle HTTP/1.1 pipelining? At a first glance it seems so from the `VecDeque` of requests and responses, but I could not tell for sure.

**Comment by georgepisaltu** [comment]
Hello @ibraheemdev ,

Yes, `micro-http` is designed to support pipelining. Please keep in mind this feature was deprecated in HTTP/2.0 and is not supported by most clients.

**Comment by ibraheemdev** [comment]
Yes, HTTP pipelining was never really put into use by browsers. It's perfect that micro-http supports it, thanks!
