### ISSUE TITLE
Pull changes from Firecracker

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/micro-http#6]
We haven't yet switched to micro-http in Firecracker and there are a few commits added to the micro-http in Firecracker since this repository was created. We need to also port the changes here.

**Comment by stappersg** [comment]
I think this issue waits for #4, _Publish micro_http to crates.io_

**Comment by andreeaflorescu** [comment]
@stappersg it's the other way around. This issue should be done before #4. We have some fixes that were added in Firecracker, but not here.

**Comment by alindima** [comment]
Firecracker now consumes micro-http from this repo. This issue was fixed by: https://github.com/firecracker-microvm/micro-http/pull/18
